# YML is case sensitive - indentation of YML is important
# i.e use spaces over TAB
apiVersion: apps/v1 # which api to use for deployment
# this is decided by the people who made it, look at documentation to know what to put there
kind: Deployment # what kind of service you want to create
# what would you like to call it
metadata:
  name: myapi-deploy # naming the deployment
spec:
  selector:
    matchLabels:
      app: myapi # look for this label to match with K8 service
  
  # Let's create a replice set of this with 3 instances/pods
  replicas: 3
  # template to use it's label for K8 service to launch in the browser
  template:
    metadata:
      labels:
        app: myapi # This label connects to the service or any other K8 components
    # Let's define the container spec
    spec:
      containers:
      - name: myapi
        image: ivangelemerov/api_upload:v1
        ports:
        - containerPort: 80